-- Ziyana Shop Supabase schema
-- Run this entire file in Supabase SQL Editor.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  name text not null default '',
  email text not null default '',
  phone text unique,
  address text not null default '',
  district text not null default '',
  role text not null default 'customer' check (role in ('customer', 'admin')),
  created_at timestamptz not null default now()
);

alter table public.profiles add column if not exists email text not null default '';
insert into public.profiles (id, name, email, phone, created_at)
select
  auth_user.id,
  coalesce(auth_user.raw_user_meta_data->>'name', ''),
  coalesce(auth_user.email, ''),
  auth_user.phone,
  auth_user.created_at
from auth.users as auth_user
on conflict (id) do update set email = excluded.email;

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  price numeric not null default 0,
  old_price numeric not null default 0,
  discount text not null default '',
  rating numeric not null default 4.8,
  category text not null default 'ফ্যাশন',
  stock integer not null default 0,
  image text not null default '',
  images jsonb not null default '[]'::jsonb,
  videos jsonb not null default '[]'::jsonb,
  description text not null default '',
  active boolean not null default true,
  created_at timestamptz not null default now()
);


create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references public.profiles(id) on delete set null,
  customer jsonb not null default '{}'::jsonb,
  district text not null default '',
  payment text not null default 'cod',
  items jsonb not null default '[]'::jsonb,
  gift jsonb,
  subtotal numeric not null default 0,
  discount numeric not null default 0,
  shipping numeric not null default 0,
  total numeric not null default 0,
  status text not null default 'pending',
  status_label text not null default 'অপেক্ষমাণ',
  courier_name text,
  booking_number text,
  tracking_url text,
  invoice_number text not null default ('ZS-' || upper(substr(replace(gen_random_uuid()::text, '-', ''), 1, 12))),
  consignment_id text,
  tracking_code text,
  courier_status text,
  courier_error text,
  courier_last_attempt_at timestamptz,
  created_at timestamptz not null default now()
);

alter table public.orders add column if not exists invoice_number text;
alter table public.orders add column if not exists district text not null default '';
alter table public.orders add column if not exists consignment_id text;
alter table public.orders add column if not exists tracking_code text;
alter table public.orders add column if not exists courier_status text;
alter table public.orders add column if not exists courier_error text;
alter table public.orders add column if not exists courier_last_attempt_at timestamptz;

update public.orders
set invoice_number = 'ZS-' || upper(replace(id::text, '-', ''))
where invoice_number is null or invoice_number = '';

alter table public.orders
  alter column invoice_number set default ('ZS-' || upper(substr(replace(gen_random_uuid()::text, '-', ''), 1, 12))),
  alter column invoice_number set not null;

create unique index if not exists orders_invoice_number_key on public.orders (invoice_number);
create unique index if not exists orders_steadfast_consignment_id_key
  on public.orders (consignment_id) where consignment_id is not null;
create index if not exists orders_courier_status_idx on public.orders (courier_status);

create table if not exists public.store_settings (
  key text primary key,
  value jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create or replace function public.is_admin()
returns boolean language sql stable security definer set search_path = public
as $$ select exists (select 1 from public.profiles where id = auth.uid() and role = 'admin'); $$;

create or replace function public.claim_steadfast_booking(p_order_id uuid)
returns setof public.orders
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.role() is distinct from 'service_role' then
    raise exception 'service role required';
  end if;

  return query
  update public.orders as order_row
  set courier_status = 'booking',
      courier_error = null,
      courier_last_attempt_at = now(),
      invoice_number = coalesce(
        nullif(order_row.invoice_number, ''),
        'ZS-' || upper(replace(order_row.id::text, '-', ''))
      )
  where order_row.id = p_order_id
    and order_row.status = 'confirmed'
    and order_row.consignment_id is null
    and coalesce(order_row.courier_status, '') in ('', 'failed')
  returning order_row.*;
end;
$$;

revoke all on function public.claim_steadfast_booking(uuid) from public, anon, authenticated;
grant execute on function public.claim_steadfast_booking(uuid) to service_role;

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public
as $$ begin
  insert into public.profiles (id, name, email, phone)
  values (new.id, coalesce(new.raw_user_meta_data->>'name', ''), coalesce(new.email, ''), new.phone)
  on conflict (id) do update set email = excluded.email;
  return new;
end; $$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users
for each row execute procedure public.handle_new_user();

drop trigger if exists on_auth_user_email_updated on auth.users;
create trigger on_auth_user_email_updated after update of email on auth.users
for each row when (old.email is distinct from new.email)
execute procedure public.handle_new_user();

alter table public.profiles enable row level security;
alter table public.products enable row level security;
alter table public.orders enable row level security;
alter table public.store_settings enable row level security;

drop policy if exists "Public can read active products" on public.products;
create policy "Public can read active products" on public.products for select using (active = true or public.is_admin());
drop policy if exists "Admins manage products" on public.products;
create policy "Admins manage products" on public.products for all using (public.is_admin()) with check (public.is_admin());

drop policy if exists "Users read own profile" on public.profiles;
create policy "Users read own profile" on public.profiles for select using (id = auth.uid() or public.is_admin());
drop policy if exists "Users update own profile" on public.profiles;
create policy "Users update own profile" on public.profiles for update using (id = auth.uid()) with check (id = auth.uid());
drop policy if exists "Admins manage profiles" on public.profiles;
create policy "Admins manage profiles" on public.profiles for all using (public.is_admin()) with check (public.is_admin());
revoke update on public.profiles from public, anon, authenticated;
grant update (name, email, phone, address, district) on public.profiles to authenticated;

drop policy if exists "Users read own orders" on public.orders;
create policy "Users read own orders" on public.orders for select using (user_id = auth.uid() or public.is_admin());
drop policy if exists "Users create own orders" on public.orders;
create policy "Users create own orders" on public.orders for insert with check (user_id = auth.uid());
drop policy if exists "Admins manage orders" on public.orders;
create policy "Admins manage orders" on public.orders for all using (public.is_admin()) with check (public.is_admin());

drop policy if exists "Public read settings" on public.store_settings;
create policy "Public read settings" on public.store_settings for select using (true);
drop policy if exists "Admins manage settings" on public.store_settings;
create policy "Admins manage settings" on public.store_settings for all using (public.is_admin()) with check (public.is_admin());

insert into public.store_settings (key, value) values
  ('ads', '[]'::jsonb), ('hero', '{}'::jsonb), ('campaign', '{}'::jsonb),
  ('mall', '{"productIds":[]}'::jsonb), ('gifts', '[]'::jsonb),
  ('coupons', '[]'::jsonb), ('shipping', '{"insideDhaka":60,"outsideDhaka":120,"freeThreshold":2499}'::jsonb)
on conflict (key) do nothing;

notify pgrst, 'reload schema';

-- After creating your account, promote that user's UUID to admin:
-- update public.profiles set role = 'admin' where id = 'YOUR_AUTH_USER_UUID';
